version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      # - add_ssh_keys:
      #     fingerprints:
      #     - "85:0b:63:a4:bc:6c:db:dc:2b:47:17:f9:e5:84:39:c5"
      - run: ruby --version

workflows:
  say-hello-workflow:
    jobs:
      - build
        
