version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Register env
          command: "NAME=fujimoto"
          environment:
            NAME: $NAME

  say-goodbye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say goodbye"
          command: "echo Good Bye"
      - run:
          name: echo env
          command: echo ${NAME}



workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          requires:
            - say-goodbye
      - say-goodbye
        
