version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-goodbye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say goodbye"
          command: "echo Good Bye"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          requires:
            - say-goobye
      - say-goodbye
        
