version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "a9:e9:fd:c5:e2:19:ff:71:e6:ab:a3:46:57:01:e7:0e"
      - run: ruby --version
      - run: 
          name: install serverspec
          command:  |
            gem install serverspec;
            gem install yaml;
            gem install rake;
            gem install highline;
      - run:
          name: execute test
          command:  |
            cd serverspec;
            rake spec;

workflows:
  say-hello-workflow:
    jobs:
      - build
        
